# AAI614: Data Science & its Applications

*Notebook 2.1: Practice with Pandas*

<a href="https://colab.research.google.com/github/harmanani/AAI614/blob/main/Week%202/Notebook2.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*This notebook contains excerpts from the [Pandas in Action](https://www.manning.com/books/pandas-in-action) by Boris Paskhaver.*

### 1. Read the file

In [98]:
import pandas as pd
import numpy as np
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

nba = pd.read_csv("https://raw.githubusercontent.com/harmanani/AAI614/main/Week%202/nba.csv")

### 1. Shared and Exclusive Attributes between Series and DataFrames

In [99]:
pd.Series([1, 2, 3]).dtype

dtype('int64')

In [100]:
nba.dtypes

Name        object
Team        object
Position    object
Birthday    object
Salary       int64
dtype: object

In [101]:
nba.dtypes.value_counts()

object    4
int64     1
Name: count, dtype: int64

In [102]:
nba.index

RangeIndex(start=0, stop=450, step=1)

In [103]:
nba.columns

Index(['Name', 'Team', 'Position', 'Birthday', 'Salary'], dtype='object')

In [104]:
nba.ndim

2

In [105]:
nba.shape

(450, 5)

In [106]:
nba.size

2250

In [107]:
nba.count()

Name        450
Team        450
Position    450
Birthday    450
Salary      450
dtype: int64

In [108]:
nba.count().sum()

np.int64(2250)

In [109]:
data = {
    "A": [1, np.nan],
    "B": [2, 3]
}

df = pd.DataFrame(data)
df

     A  B
0  1.0  2
1  NaN  3

In [110]:
df.size

4

In [111]:
df.count()

A    1
B    2
dtype: int64

In [112]:
df.count().sum()

np.int64(3)

### 2. Shared Methods between Series and DataFrames

In [113]:
nba.head(2)

             Name                Team Position Birthday   Salary
0    Shake Milton  Philadelphia 76ers       SG  9/26/96  1445697
1  Christian Wood     Detroit Pistons       PF  9/27/95  1645357

In [114]:
nba.tail(n = 3)

              Name                 Team Position  Birthday    Salary
447    Robin Lopez      Milwaukee Bucks        C    4/1/88   4767000
448  Collin Sexton  Cleveland Cavaliers       PG    1/4/99   4764960
449    Ricky Rubio         Phoenix Suns       PG  10/21/90  16200000

In [115]:
nba.tail()

              Name                 Team Position  Birthday    Salary
445  Austin Rivers      Houston Rockets       PG    8/1/92   2174310
446    Harry Giles     Sacramento Kings       PF   4/22/98   2578800
447    Robin Lopez      Milwaukee Bucks        C    4/1/88   4767000
448  Collin Sexton  Cleveland Cavaliers       PG    1/4/99   4764960
449    Ricky Rubio         Phoenix Suns       PG  10/21/90  16200000

In [116]:
nba.sample(3)

               Name             Team Position  Birthday    Salary
404  Doug McDermott   Indiana Pacers       PF    1/3/92   7333333
59     Marcus Smart   Boston Celtics       PG    3/6/94  12553571
326   Dragan Bender  Milwaukee Bucks       PF  11/17/97   1678854

In [117]:
nba.nunique()

Name        450
Team         30
Position      9
Birthday    430
Salary      269
dtype: int64

In [118]:
nba.max()

Name            Zylan Cheatham
Team        Washington Wizards
Position                    SG
Birthday                9/9/93
Salary                40231758
dtype: object

In [119]:
nba.min()

Name         Aaron Gordon
Team        Atlanta Hawks
Position                C
Birthday          1/10/98
Salary              79568
dtype: object

In [120]:
nba.nlargest(n = 4, columns = "Salary")

                  Name                   Team Position  Birthday    Salary
205      Stephen Curry  Golden State Warriors       PG   3/14/88  40231758
38          Chris Paul  Oklahoma City Thunder       PG    5/6/85  38506482
219  Russell Westbrook        Houston Rockets       PG  11/12/88  38506482
251          John Wall     Washington Wizards       PG    9/6/90  38199000

In [121]:
nba['Birthday'] = pd.to_datetime(nba['Birthday'])

/tmp/ipykernel_602/101016257.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  nba['Birthday'] = pd.to_datetime(nba['Birthday'])

In [122]:
nba.nsmallest(n = 3, columns = ["Birthday"])

              Name             Team Position   Birthday   Salary
98    Vince Carter    Atlanta Hawks       PF 1977-01-26  2564753
196  Udonis Haslem       Miami Heat        C 1980-06-09  2564753
262    Kyle Korver  Milwaukee Bucks       PF 1981-03-17  6004753

#### The following should give an error.  No need to panic :-)

In [123]:
#nba.sum()

In [124]:
nba.sum(numeric_only = True)

Salary    3444112694
dtype: int64

In [125]:
nba.mean(numeric_only = True)

Salary    7.653584e+06
dtype: float64

In [126]:
nba.median(numeric_only = True)

Salary    3303074.5
dtype: float64

In [127]:
nba.mode(numeric_only = True)

   Salary
0   79568

In [128]:
nba.std(numeric_only = True)

Salary    9.288810e+06
dtype: float64

## 3. Sorting a DataFrame

### 3.1 Sorting by Single Column

In [129]:
# The two lines below are equivalent
nba.sort_values("Name")
nba.sort_values(by = "Name")

                  Name                   Team Position   Birthday    Salary
52        Aaron Gordon          Orlando Magic       PF 1995-09-16  19863636
101      Aaron Holiday         Indiana Pacers       PG 1996-09-30   2239200
437        Abdel Nader  Oklahoma City Thunder       SF 1993-09-25   1618520
81         Adam Mokoka          Chicago Bulls        G 1998-07-18     79568
399  Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
..                 ...                    ...      ...        ...       ...
159        Zach LaVine          Chicago Bulls       PG 1995-03-10  19500000
302       Zach Norvell     Los Angeles Lakers       SG 1997-12-09     79568
312       Zhaire Smith     Philadelphia 76ers       SG 1999-06-04   3058800
137    Zion Williamson   New Orleans Pelicans        F 2000-07-06   9757440
248     Zylan Cheatham   New Orleans Pelicans       SF 1995-11-17     79568

[450 rows x 5 columns]

In [130]:
nba.sort_values("Name", ascending = False).head()

                Name                  Team Position   Birthday    Salary
248   Zylan Cheatham  New Orleans Pelicans       SF 1995-11-17     79568
137  Zion Williamson  New Orleans Pelicans        F 2000-07-06   9757440
312     Zhaire Smith    Philadelphia 76ers       SG 1999-06-04   3058800
302     Zach Norvell    Los Angeles Lakers       SG 1997-12-09     79568
159      Zach LaVine         Chicago Bulls       PG 1995-03-10  19500000

In [131]:
nba.sort_values("Birthday", ascending = False).head()

                    Name                  Team Position   Birthday   Salary
136      Sekou Doumbouya       Detroit Pistons       SF 2000-12-23  3285120
432  Talen Horton-Tucker    Los Angeles Lakers       GF 2000-11-25   898310
137      Zion Williamson  New Orleans Pelicans        F 2000-07-06  9757440
313           RJ Barrett       New York Knicks       SG 2000-06-14  7839960
392         Jalen Lecque          Phoenix Suns        G 2000-06-13   898310

### 4.2 Sorting by Multiple Columns

In [132]:
nba.sort_values(by = ["Team", "Name"])

                Name                Team Position   Birthday    Salary
359         Alex Len       Atlanta Hawks        C 1993-06-16   4160000
167     Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
276  Brandon Goodwin       Atlanta Hawks       PG 1995-10-02     79568
438   Bruno Fernando       Atlanta Hawks        C 1998-08-15   1400000
194      Cam Reddish       Atlanta Hawks       SF 1999-09-01   4245720
..               ...                 ...      ...        ...       ...
418     Jordan McRae  Washington Wizards       PG 1991-03-28   1645357
273  Justin Robinson  Washington Wizards       PG 1997-10-12    898310
428    Moritz Wagner  Washington Wizards        C 1997-04-26   2063520
21     Rui Hachimura  Washington Wizards       PF 1998-02-08   4469160
36     Thomas Bryant  Washington Wizards        C 1997-07-31   8000000

[450 rows x 5 columns]

In [133]:
nba.sort_values(["Team", "Name"], ascending = False)

                Name                Team Position   Birthday    Salary
36     Thomas Bryant  Washington Wizards        C 1997-07-31   8000000
21     Rui Hachimura  Washington Wizards       PF 1998-02-08   4469160
428    Moritz Wagner  Washington Wizards        C 1997-04-26   2063520
273  Justin Robinson  Washington Wizards       PG 1997-10-12    898310
418     Jordan McRae  Washington Wizards       PG 1991-03-28   1645357
..               ...                 ...      ...        ...       ...
194      Cam Reddish       Atlanta Hawks       SF 1999-09-01   4245720
438   Bruno Fernando       Atlanta Hawks        C 1998-08-15   1400000
276  Brandon Goodwin       Atlanta Hawks       PG 1995-10-02     79568
167     Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
359         Alex Len       Atlanta Hawks        C 1993-06-16   4160000

[450 rows x 5 columns]

In [134]:
nba.sort_values(
    by = ["Team", "Salary"], ascending = [True, False]
)

                  Name                Team Position   Birthday    Salary
111   Chandler Parsons       Atlanta Hawks       SF 1988-10-25  25102512
28         Evan Turner       Atlanta Hawks       PG 1988-10-27  18606556
167       Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
213    De'Andre Hunter       Atlanta Hawks       SF 1997-12-02   7068360
339      Jabari Parker       Atlanta Hawks       PF 1995-03-15   6500000
..                 ...                 ...      ...        ...       ...
80         Isaac Bonga  Washington Wizards       PG 1999-11-08   1416852
399  Admiral Schofield  Washington Wizards       SF 1997-03-30   1000000
273    Justin Robinson  Washington Wizards       PG 1997-10-12    898310
283   Garrison Mathews  Washington Wizards       SG 1996-10-24     79568
353      Chris Chiozza  Washington Wizards       PG 1995-11-21     79568

[450 rows x 5 columns]

In [135]:
nba = nba.sort_values(
    by = ["Team", "Salary"],
    ascending = [True, False]
)

## 5 Sorting by Index

In [136]:
nba.head()

                 Name           Team Position   Birthday    Salary
111  Chandler Parsons  Atlanta Hawks       SF 1988-10-25  25102512
28        Evan Turner  Atlanta Hawks       PG 1988-10-27  18606556
167      Allen Crabbe  Atlanta Hawks       SG 1992-04-09  18500000
213   De'Andre Hunter  Atlanta Hawks       SF 1997-12-02   7068360
339     Jabari Parker  Atlanta Hawks       PF 1995-03-15   6500000

### 5.1 Sorting by Row Index

In [137]:
# The two lines below are equivalent
nba.sort_index().head()
nba.sort_index(ascending = True).head()

             Name                Team Position   Birthday   Salary
0    Shake Milton  Philadelphia 76ers       SG 1996-09-26  1445697
1  Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
2   PJ Washington   Charlotte Hornets       PF 1998-08-23  3831840
3    Derrick Rose     Detroit Pistons       PG 1988-10-04  7317074
4   Marial Shayok  Philadelphia 76ers        G 1995-07-26    79568

In [138]:
nba.sort_index(ascending = False).head()

              Name                 Team Position   Birthday    Salary
449    Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000
448  Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
447    Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
446    Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
445  Austin Rivers      Houston Rockets       PG 1992-08-01   2174310

In [139]:
nba = nba.sort_index()

### 5.2 Sorting by Column Index

In [140]:
# The two lines below are equivalent
nba.sort_index(axis = "columns").head()
nba.sort_index(axis = 1).head()

    Birthday            Name Position   Salary                Team
0 1996-09-26    Shake Milton       SG  1445697  Philadelphia 76ers
1 1995-09-27  Christian Wood       PF  1645357     Detroit Pistons
2 1998-08-23   PJ Washington       PF  3831840   Charlotte Hornets
3 1988-10-04    Derrick Rose       PG  7317074     Detroit Pistons
4 1995-07-26   Marial Shayok        G    79568  Philadelphia 76ers

In [141]:
nba.sort_index(axis = "columns", ascending = False).head()

                 Team   Salary Position            Name   Birthday
0  Philadelphia 76ers  1445697       SG    Shake Milton 1996-09-26
1     Detroit Pistons  1645357       PF  Christian Wood 1995-09-27
2   Charlotte Hornets  3831840       PF   PJ Washington 1998-08-23
3     Detroit Pistons  7317074       PG    Derrick Rose 1988-10-04
4  Philadelphia 76ers    79568        G   Marial Shayok 1995-07-26

## 5.3 Setting a New Index

In [142]:
# The two lines below are equivalent
nba.set_index(keys = "Name")

                               Team Position   Birthday    Salary
Name
Shake Milton     Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

In [143]:
nba.set_index("Name")

                               Team Position   Birthday    Salary
Name
Shake Milton     Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

## 6 Selecting Columns and Rows from a DataFrame

### 6.1 Selecting a Single Column from a DataFrame

In [144]:
nba.Salary

0       1445697
1       1645357
2       3831840
3       7317074
4         79568
         ...
445     2174310
446     2578800
447     4767000
448     4764960
449    16200000
Name: Salary, Length: 450, dtype: int64

In [145]:
nba["Position"]

0      SG
1      PF
2      PF
3      PG
4       G
       ..
445    PG
446    PF
447     C
448    PG
449    PG
Name: Position, Length: 450, dtype: object

### 6.2 Selecting Multiple Columns from a DataFrame

In [146]:
nba[["Salary", "Birthday"]].head()

    Salary   Birthday
0  1445697 1996-09-26
1  1645357 1995-09-27
2  3831840 1998-08-23
3  7317074 1988-10-04
4    79568 1995-07-26

In [147]:
nba[["Birthday", "Salary"]].head()

    Birthday   Salary
0 1996-09-26  1445697
1 1995-09-27  1645357
2 1998-08-23  3831840
3 1988-10-04  7317074
4 1995-07-26    79568

In [148]:
nba.select_dtypes(include = "object")

               Name                 Team Position
0      Shake Milton   Philadelphia 76ers       SG
1    Christian Wood      Detroit Pistons       PF
2     PJ Washington    Charlotte Hornets       PF
3      Derrick Rose      Detroit Pistons       PG
4     Marial Shayok   Philadelphia 76ers        G
..              ...                  ...      ...
445   Austin Rivers      Houston Rockets       PG
446     Harry Giles     Sacramento Kings       PF
447     Robin Lopez      Milwaukee Bucks        C
448   Collin Sexton  Cleveland Cavaliers       PG
449     Ricky Rubio         Phoenix Suns       PG

[450 rows x 3 columns]

In [149]:
nba.select_dtypes(exclude = ["object", "int"])

      Birthday
0   1996-09-26
1   1995-09-27
2   1998-08-23
3   1988-10-04
4   1995-07-26
..         ...
445 1992-08-01
446 1998-04-22
447 1988-04-01
448 1999-01-04
449 1990-10-21

[450 rows x 1 columns]

## 7 Selecting Rows from a DataFrame

### 7.1 Extracting Rows by Index Label

In [150]:
nba

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [151]:
nba.index = nba["Name"]
nba = nba.set_index('Name', drop = True)

In [152]:
nba.loc["LeBron James"]

Team         Los Angeles Lakers
Position                     PF
Birthday    1984-12-30 00:00:00
Salary                 37436858
Name: LeBron James, dtype: object

In [153]:
nba.loc[["Kawhi Leonard", "Paul George"]]

                               Team Position   Birthday    Salary
Name
Kawhi Leonard  Los Angeles Clippers       SF 1991-06-29  32742000
Paul George    Los Angeles Clippers       SF 1990-05-02  33005556

In [154]:
nba.loc[["Paul George", "Kawhi Leonard"]]

                               Team Position   Birthday    Salary
Name
Paul George    Los Angeles Clippers       SF 1990-05-02  33005556
Kawhi Leonard  Los Angeles Clippers       SF 1991-06-29  32742000

In [155]:
nba.sort_index().loc["Otto Porter":"Patrick Beverley"]

                                  Team Position   Birthday    Salary
Name
Otto Porter              Chicago Bulls       SF 1993-06-03  27250576
PJ Dozier               Denver Nuggets       PG 1996-10-25     79568
PJ Washington        Charlotte Hornets       PF 1998-08-23   3831840
Pascal Siakam          Toronto Raptors       PF 1994-04-02   2351838
Pat Connaughton        Milwaukee Bucks       SG 1993-01-06   1723050
Patrick Beverley  Los Angeles Clippers       PG 1988-07-12  12345680

In [156]:
players = ["Otto Porter", "PJ Dozier", "PJ Washington"]
players[0:2]

['Otto Porter', 'PJ Dozier']

In [157]:
nba.sort_index().loc["Zach Collins":]

                                   Team Position   Birthday    Salary
Name
Zach Collins     Portland Trail Blazers        C 1997-11-19   4240200
Zach LaVine               Chicago Bulls       PG 1995-03-10  19500000
Zach Norvell         Los Angeles Lakers       SG 1997-12-09     79568
Zhaire Smith         Philadelphia 76ers       SG 1999-06-04   3058800
Zion Williamson    New Orleans Pelicans        F 2000-07-06   9757440
Zylan Cheatham     New Orleans Pelicans       SF 1995-11-17     79568

In [158]:
nba.sort_index().loc[:"Al Horford"]

                                    Team Position   Birthday    Salary
Name
Aaron Gordon               Orlando Magic       PF 1995-09-16  19863636
Aaron Holiday             Indiana Pacers       PG 1996-09-30   2239200
Abdel Nader        Oklahoma City Thunder       SF 1993-09-25   1618520
Adam Mokoka                Chicago Bulls        G 1998-07-18     79568
Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
Al Horford            Philadelphia 76ers        C 1986-06-03  28000000

**NOTE**: I've commented out the code below so that the Notebook can run without raising an error.

In [159]:
#nba.loc["Bugs Bunny"]

### 7.2 Extracting Rows by Index Position

In [160]:
nba.iloc[300]

Team             Denver Nuggets
Position                     PF
Birthday    1999-04-03 00:00:00
Salary                  1416852
Name: Jarred Vanderbilt, dtype: object

In [161]:
nba.iloc[[100, 200, 300, 400]]

                                Team Position   Birthday   Salary
Name
Brian Bowen           Indiana Pacers       SG 1998-10-02    79568
Marco Belinelli    San Antonio Spurs       SF 1986-03-25  5846154
Jarred Vanderbilt     Denver Nuggets       PF 1999-04-03  1416852
Louis King           Detroit Pistons        F 1999-04-06    79568

In [162]:
nba.iloc[400:404]

                                    Team Position   Birthday    Salary
Name
Louis King               Detroit Pistons        F 1999-04-06     79568
Kostas Antetokounmpo  Los Angeles Lakers       PF 1997-11-20     79568
Rodions Kurucs             Brooklyn Nets       PF 1998-02-05   1699236
Spencer Dinwiddie          Brooklyn Nets       PG 1993-04-06  10605600

In [163]:
nba.iloc[:2]

                              Team Position   Birthday   Salary
Name
Shake Milton    Philadelphia 76ers       SG 1996-09-26  1445697
Christian Wood     Detroit Pistons       PF 1995-09-27  1645357

In [164]:
nba.iloc[447:]

                              Team Position   Birthday    Salary
Name
Robin Lopez        Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio           Phoenix Suns       PG 1990-10-21  16200000

In [165]:
nba.iloc[-10:-6]

                                    Team Position   Birthday   Salary
Name
Jared Dudley          Los Angeles Lakers       PF 1985-07-10  2564753
Max Strus                  Chicago Bulls       SG 1996-03-28    79568
Kevon Looney       Golden State Warriors        C 1996-02-06  4464286
Willy Hernangomez      Charlotte Hornets        C 1994-05-27  1557250

In [166]:
nba.iloc[0:10:2]

                             Team Position   Birthday    Salary
Name
Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
PJ Washington   Charlotte Hornets       PF 1998-08-23   3831840
Marial Shayok  Philadelphia 76ers        G 1995-07-26     79568
Kendrick Nunn          Miami Heat       SG 1995-08-03   1416852
Brook Lopez       Milwaukee Bucks        C 1988-04-01  12093024

### 7.3 Extracting Values from Specific Columns

In [167]:
nba['Team'].loc["Giannis Antetokounmpo"]

'Milwaukee Bucks'

In [168]:
nba.loc["James Harden", ["Position", "Birthday"]]

Position                     PG
Birthday    1989-08-26 00:00:00
Name: James Harden, dtype: object

In [169]:
nba.loc[
    ["Russell Westbrook", "Anthony Davis"],
    ["Team", "Salary"]
]

                                 Team    Salary
Name
Russell Westbrook     Houston Rockets  38506482
Anthony Davis      Los Angeles Lakers  27093019

In [170]:
nba.loc["Joel Embiid", "Position":"Salary"]

Position                      C
Birthday    1994-03-16 00:00:00
Salary                 27504630
Name: Joel Embiid, dtype: object

In [171]:
nba.loc["Joel Embiid", "Salary":"Position"]

Series([], Name: Joel Embiid, dtype: object)

In [172]:
nba.iloc[57, 3]

np.int64(796806)

In [173]:
nba.iloc[100:104, :3]

                             Team Position   Birthday
Name
Brian Bowen        Indiana Pacers       SG 1998-10-02
Aaron Holiday      Indiana Pacers       PG 1996-09-30
Troy Daniels   Los Angeles Lakers       SG 1991-07-15
Buddy Hield      Sacramento Kings       SG 1992-12-17

In [174]:
nba.at["Austin Rivers", "Birthday"]

Timestamp('1992-08-01 00:00:00')

In [175]:
nba.iat[263, 1]

'PF'

In [176]:
%%timeit
nba.at["Austin Rivers", "Birthday"]

7.82 µs ± 167 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [177]:
%%timeit
nba.loc["Austin Rivers", "Birthday"]

13.9 µs ± 2.83 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [178]:
%%timeit
nba.iat[263, 1]

14.6 µs ± 3.33 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [179]:
%%timeit
nba.iloc[263, 1]

18.8 µs ± 3.77 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)

## 8 Extracting Values from Series

In [180]:
nba["Salary"].loc["Damian Lillard"]

np.int64(29802321)

In [181]:
nba["Salary"].at["Damian Lillard"]

np.int64(29802321)

In [182]:
nba["Salary"].iloc[234]

np.int64(2033160)

In [183]:
nba["Salary"].iat[234]

np.int64(2033160)

## 9 Renaming Columns or Rows

In [184]:
nba.columns

Index(['Team', 'Position', 'Birthday', 'Salary'], dtype='object')

In [185]:
nba.columns = ["Team", "Position", "Date of Birth", "Pay"]
nba.head(1)

                            Team Position Date of Birth      Pay
Name
Shake Milton  Philadelphia 76ers       SG    1996-09-26  1445697

In [186]:
nba.rename(columns = { "Date of Birth": "Birthday" })

                               Team Position   Birthday       Pay
Name
Shake Milton     Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

In [187]:
nba = nba.rename(columns = { "Date of Birth": "Birthday" })

In [188]:
nba.loc["Giannis Antetokounmpo"]

Team            Milwaukee Bucks
Position                     PF
Birthday    1994-12-06 00:00:00
Pay                    25842697
Name: Giannis Antetokounmpo, dtype: object

In [189]:
nba = nba.rename(
    index = { "Giannis Antetokounmpo": "Greek Freak" }
)

In [190]:
nba.loc["Greek Freak"]

Team            Milwaukee Bucks
Position                     PF
Birthday    1994-12-06 00:00:00
Pay                    25842697
Name: Greek Freak, dtype: object

## 10 Resetting an Index

In [191]:
nba.set_index("Team").head()

                   Position   Birthday      Pay
Team
Philadelphia 76ers       SG 1996-09-26  1445697
Detroit Pistons          PF 1995-09-27  1645357
Charlotte Hornets        PF 1998-08-23  3831840
Detroit Pistons          PG 1988-10-04  7317074
Philadelphia 76ers        G 1995-07-26    79568

In [192]:
nba.reset_index().head()

             Name                Team Position   Birthday      Pay
0    Shake Milton  Philadelphia 76ers       SG 1996-09-26  1445697
1  Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
2   PJ Washington   Charlotte Hornets       PF 1998-08-23  3831840
3    Derrick Rose     Detroit Pistons       PG 1988-10-04  7317074
4   Marial Shayok  Philadelphia 76ers        G 1995-07-26    79568

In [193]:
nba.reset_index().set_index("Team").head()

                              Name Position   Birthday      Pay
Team
Philadelphia 76ers    Shake Milton       SG 1996-09-26  1445697
Detroit Pistons     Christian Wood       PF 1995-09-27  1645357
Charlotte Hornets    PJ Washington       PF 1998-08-23  3831840
Detroit Pistons       Derrick Rose       PG 1988-10-04  7317074
Philadelphia 76ers   Marial Shayok        G 1995-07-26    79568

In [194]:
nba = nba.reset_index().set_index("Team")